//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_CABECERA_COTIZACION
    {
        public CP_CABECERA_COTIZACION()
        {
            this.CP_COTIZACION_X_PEDIDO = new HashSet<CP_COTIZACION_X_PEDIDO>();
            this.CP_DETALLE_COTIZACION = new HashSet<CP_DETALLE_COTIZACION>();
            this.CP_ORDEN_COMPRA = new HashSet<CP_ORDEN_COMPRA>();
        }
    
        public decimal numero { get; set; }
        public Nullable<decimal> id_provedor { get; set; }
        public Nullable<decimal> id_user_aprovacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> cod_estado { get; set; }
    
        public virtual CP_ESTADO CP_ESTADO { get; set; }
        public virtual ICollection<CP_COTIZACION_X_PEDIDO> CP_COTIZACION_X_PEDIDO { get; set; }
        public virtual ICollection<CP_DETALLE_COTIZACION> CP_DETALLE_COTIZACION { get; set; }
        public virtual ICollection<CP_ORDEN_COMPRA> CP_ORDEN_COMPRA { get; set; }
    }
}
