//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_CABECERA_DESPACHO
    {
        public CP_CABECERA_DESPACHO()
        {
            this.CP_DETALLE_DESPACHO = new HashSet<CP_DETALLE_DESPACHO>();
        }
    
        public decimal numero { get; set; }
        public Nullable<System.DateTime> fecha_despacho { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<decimal> numero_orden_compra { get; set; }
        public Nullable<decimal> id_proveedor { get; set; }
        public Nullable<decimal> id_estado { get; set; }
    
        public virtual ICollection<CP_DETALLE_DESPACHO> CP_DETALLE_DESPACHO { get; set; }
    }
}
