//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_CABECERA_PEDIDO
    {
        public CP_CABECERA_PEDIDO()
        {
            this.CP_COTIZACION_X_PEDIDO = new HashSet<CP_COTIZACION_X_PEDIDO>();
            this.CP_DETALLE_PEDIDO = new HashSet<CP_DETALLE_PEDIDO>();
        }
    
        public decimal numero { get; set; }
        public Nullable<decimal> id_responsable { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ICollection<CP_COTIZACION_X_PEDIDO> CP_COTIZACION_X_PEDIDO { get; set; }
        public virtual ICollection<CP_DETALLE_PEDIDO> CP_DETALLE_PEDIDO { get; set; }
    }
}
