//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_COTIZACION_X_PEDIDO
    {
        public decimal codigo { get; set; }
        public decimal numero_pedido { get; set; }
        public decimal numero_cotizacion { get; set; }
    
        public virtual CP_CABECERA_COTIZACION CP_CABECERA_COTIZACION { get; set; }
        public virtual CP_CABECERA_PEDIDO CP_CABECERA_PEDIDO { get; set; }
    }
}
