//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_DETALLE_COTIZACION
    {
        public decimal numero { get; set; }
        public decimal linea { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> id_producto { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
    
        public virtual CP_CABECERA_COTIZACION CP_CABECERA_COTIZACION { get; set; }
    }
}
