//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_ESTADO
    {
        public CP_ESTADO()
        {
            this.CP_CABECERA_COTIZACION = new HashSet<CP_CABECERA_COTIZACION>();
        }
    
        public decimal codigo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<CP_CABECERA_COTIZACION> CP_CABECERA_COTIZACION { get; set; }
    }
}
