//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_M_PROVEEDOR
    {
        public decimal Codigo_Proveedor { get; set; }
        public string nombre { get; set; }
        public string razonSocial { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string responsable_legal { get; set; }
        public Nullable<bool> contabilidad { get; set; }
        public string ruc { get; set; }
        public string cedula_pass { get; set; }
        public Nullable<decimal> id_tipo_producto { get; set; }
    }
}
