//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_ORDEN_COMPRA
    {
        public CP_ORDEN_COMPRA()
        {
            this.CP_ORDEN_COMPRA_DETALLE = new HashSet<CP_ORDEN_COMPRA_DETALLE>();
        }
    
        public decimal numero { get; set; }
        public Nullable<System.DateTime> fecha_generacion { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<decimal> id_responsable { get; set; }
        public Nullable<System.DateTime> fecha_aprovacion { get; set; }
        public Nullable<decimal> numero_cotizacion { get; set; }
        public Nullable<decimal> subtoral { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual CP_CABECERA_COTIZACION CP_CABECERA_COTIZACION { get; set; }
        public virtual ICollection<CP_ORDEN_COMPRA_DETALLE> CP_ORDEN_COMPRA_DETALLE { get; set; }
    }
}
