//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloFacturacion.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAVEntities1 : DbContext
    {
        public SAVEntities1()
            : base("name=SAVEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CP_CABECERA_COTIZACION> CP_CABECERA_COTIZACION { get; set; }
        public DbSet<CP_CABECERA_DESPACHO> CP_CABECERA_DESPACHO { get; set; }
        public DbSet<CP_CABECERA_PEDIDO> CP_CABECERA_PEDIDO { get; set; }
        public DbSet<CP_COTIZACION_X_PEDIDO> CP_COTIZACION_X_PEDIDO { get; set; }
        public DbSet<CP_DETALLE_COTIZACION> CP_DETALLE_COTIZACION { get; set; }
        public DbSet<CP_DETALLE_DESPACHO> CP_DETALLE_DESPACHO { get; set; }
        public DbSet<CP_DETALLE_PEDIDO> CP_DETALLE_PEDIDO { get; set; }
        public DbSet<CP_ESTADO> CP_ESTADO { get; set; }
        public DbSet<CP_M_PROVEEDOR> CP_M_PROVEEDOR { get; set; }
        public DbSet<CP_ORDEN_COMPRA> CP_ORDEN_COMPRA { get; set; }
        public DbSet<CP_ORDEN_COMPRA_DETALLE> CP_ORDEN_COMPRA_DETALLE { get; set; }
    }
}
